using System.Data;
using DataLakeIngestionService.Core.Enums;
using DataLakeIngestionService.Core.Exceptions;
using DataLakeIngestionService.Core.Interfaces.DataExtraction;
using Microsoft.Extensions.Logging;

namespace DataLakeIngestionService.Infrastructure.DataExtraction;

/// <summary>
/// Data source implementation that generates data using registered IDotNetDataProvider implementations.
/// This allows C# code-based data generation without requiring a database connection.
/// </summary>
public class DotNetDataSource : IDataSource
{
    private readonly ILogger<DotNetDataSource> _logger;
    private readonly IDotNetDataProviderFactory _providerFactory;

    public DotNetDataSource(
        ILogger<DotNetDataSource> logger,
        IDotNetDataProviderFactory providerFactory)
    {
        _logger = logger;
        _providerFactory = providerFactory;
    }

    /// <summary>
    /// Executes data extraction using a registered IDotNetDataProvider.
    /// </summary>
    /// <param name="connectionString">Not used for DotNet source, can be empty.</param>
    /// <param name="query">The provider name to invoke (matches IDotNetDataProvider.ProviderName).</param>
    /// <param name="extractionType">Expected to be CodeGenerator for DotNet sources.</param>
    /// <param name="parameters">Parameters to pass to the provider.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>DataTable generated by the provider.</returns>
    public async Task<DataTable> ExtractAsync(
        Func<string> connectionStringFactory,
        string query,
        ExtractionType extractionType,
        Dictionary<string, object>? parameters,
        CancellationToken cancellationToken)
    {
        var providerName = query;

        if (string.IsNullOrWhiteSpace(providerName))
        {
            var availableProviders = string.Join(", ", _providerFactory.GetAvailableProviders());
            throw new ExtractionException(
                $"Provider name (query parameter) is required for DotNet data source. Available providers: {availableProviders}");
        }

        _logger.LogInformation("Executing DotNet data provider: {ProviderName}", providerName);

        try
        {
            var provider = _providerFactory.Create(providerName);
            _logger.LogDebug("Invoking provider {ProviderName} with {ParamCount} parameters",
                providerName, parameters?.Count ?? 0);

            if (parameters != null)
            {
                foreach (var param in parameters)
                {
                    _logger.LogDebug("  Parameter: {Name} = {Value} (Type: {Type})",
                        param.Key,
                        param.Value,
                        param.Value?.GetType().Name ?? "null");
                }
            }

            var dataTable = await provider.GenerateDataAsync(parameters, cancellationToken);

            _logger.LogInformation(
                "DotNet provider {ProviderName} generated {RowCount} rows with {ColumnCount} columns",
                providerName, dataTable.Rows.Count, dataTable.Columns.Count);

            // Log schema for debugging
            _logger.LogDebug("Generated DataTable schema ({ColumnCount} columns):", dataTable.Columns.Count);
            foreach (DataColumn col in dataTable.Columns)
            {
                var sampleValue = dataTable.Rows.Count > 0 ? dataTable.Rows[0][col] : null;
                var sampleValueType = sampleValue == DBNull.Value ? "DBNull" : sampleValue?.GetType().Name ?? "null";

                _logger.LogDebug("  Column '{Name}': DataType={Type}, AllowDBNull={AllowNull}, SampleType={SampleType}",
                    col.ColumnName,
                    col.DataType.Name,
                    col.AllowDBNull,
                    sampleValueType);
            }

            return dataTable;
        }
        catch (OperationCanceledException)
        {
            _logger.LogWarning("DotNet data provider {ProviderName} was cancelled", providerName);
            throw;
        }
        catch (ArgumentException ex)
        {
            // Re-throw ArgumentException from factory (provider not found) as ExtractionException
            _logger.LogError(ex, "DotNet data provider {ProviderName} not found", providerName);
            throw new ExtractionException(ex.Message, ex);
        }
        catch (Exception ex) when (ex is not ExtractionException)
        {
            _logger.LogError(ex, "DotNet data provider {ProviderName} failed", providerName);
            throw new ExtractionException($"DotNet provider '{providerName}' failed: {ex.Message}", ex);
        }
    }
}
